version: '3.3'
services:
   dbdiff:
     build: ./dockerDBDiff
     image: coletivo_java:dbdiff
     volumes:     
       - /home/superBits/devTools/DBDiff/novoBanco:/home/superBits/devTools/DBDiff/novoBanco/
       - /home/superBits/devTools/DBDiff/referencia:/home/superBits/devTools/DBDiff/referencia/
       - /home/superBits/devTools/DBDiff/resultado:/home/superBits/devTools/DBDiff/resultado/
     
   mysqlab:
     container_name: bancoSBanaliseBanco
     image: mysql:5.7
     restart: always
     volumes:
       - ./persistenciaBanco:/var/lib/mysql:Z
     environment:
       MYSQL_ROOT_PASSWORD: senhaDev#123
       MYSQL_DATABASE: testes
       MYSQL_USER: usuarioTeste
       MYSQL_PASSWORD: senhaDev#123
     

  
